. e add test report
Co-Authored-By: Jay Bazuzi <1259628+JayBazuzi@users.noreply.github.com>

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -13,7 +13,13 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Test
-        run: dotnet test src
+        run: dotnet test src --logger "junit;LogFilePath=TestResults/test-results.xml"
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'src/**/TestResults/test-results.xml'
+          detailed_summary: true
 
       - name: Upload NuGet Packages
         uses: actions/upload-artifact@v4
